<template>
  <div>
    <scroll class="content">
      <h2>施工中...</h2>
      <ul>
        <li>信息列表1</li>
        <li>信息列表2</li>
        <li>信息列表3</li>
        <li>信息列表4</li>
        <li>信息列表5</li>
        <li>信息列表6</li>
        <li>信息列表7</li>
        <li>信息列表8</li>
        <li>信息列表9</li>
        <li>信息列表10</li>
        <li>信息列表11</li>
        <li>信息列表12</li>
        <li>信息列表13</li>
        <li>信息列表14</li>
        <li>信息列表15</li>
        <li>信息列表16</li>
        <li>信息列表17</li>
        <li>信息列表18</li>
        <li>信息列表19</li>
        <li>信息列表20</li>
        <li>信息列表21</li>
        <li>信息列表22</li>
        <li>信息列表23</li>
        <li>信息列表24</li>
        <li>信息列表25</li>
        <li>信息列表26</li>
        <li>信息列表27</li>
        <li>信息列表28</li>
        <li>信息列表29</li>
        <li>信息列表30</li>
        <li>信息列表31</li>
        <li>信息列表32</li>
        <li>信息列表33</li>
        <li>信息列表34</li>
        <li>信息列表35</li>
        <li>信息列表36</li>
        <li>信息列表37</li>
        <li>信息列表38</li>
        <li>信息列表39</li>
        <li>信息列表40</li>
        <li>信息列表41</li>
        <li>信息列表42</li>
        <li>信息列表43</li>
        <li>信息列表44</li>
        <li>信息列表45</li>
        <li>信息列表46</li>
        <li>信息列表47</li>
        <li>信息列表48</li>
        <li>信息列表49</li>
        <li>信息列表50</li>
        <li>信息列表51</li>
        <li>信息列表52</li>
        <li>信息列表53</li>
        <li>信息列表54</li>
        <li>信息列表55</li>
        <li>信息列表56</li>
        <li>信息列表57</li>
        <li>信息列表58</li>
        <li>信息列表59</li>
        <li>信息列表60</li>
        <li>信息列表61</li>
        <li>信息列表62</li>
        <li>信息列表63</li>
        <li>信息列表64</li>
        <li>信息列表65</li>
        <li>信息列表66</li>
        <li>信息列表67</li>
        <li>信息列表68</li>
        <li>信息列表69</li>
        <li>信息列表70</li>
        <li>信息列表71</li>
        <li>信息列表72</li>
        <li>信息列表73</li>
        <li>信息列表74</li>
        <li>信息列表75</li>
        <li>信息列表76</li>
        <li>信息列表77</li>
        <li>信息列表78</li>
        <li>信息列表79</li>
        <li>信息列表80</li>
        <li>信息列表81</li>
        <li>信息列表82</li>
        <li>信息列表83</li>
        <li>信息列表84</li>
        <li>信息列表85</li>
        <li>信息列表86</li>
        <li>信息列表87</li>
        <li>信息列表88</li>
        <li>信息列表89</li>
        <li>信息列表90</li>
        <li>信息列表91</li>
        <li>信息列表92</li>
        <li>信息列表93</li>
        <li>信息列表94</li>
        <li>信息列表95</li>
        <li>信息列表96</li>
        <li>信息列表97</li>
        <li>信息列表98</li>
        <li>信息列表99</li>
        <li>信息列表100</li>
      </ul>
    </scroll>
  </div>
</template>

<script>

  import Scroll from "../../components/common/scroll/Scroll";
  export default {
    name: "Profile",
    components:{
      Scroll
    }
  }
</script>

<style scoped>
  .content{
    height: 300px;
    background-color: red;
    overflow: hidden;

  }
</style>
